server:
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #Rutas de cada servicio:
        - id: matchmaking-service
          uri: lb://matchmaking-service
          predicates:
            - Path=/api/players/**, /api/login, /api/filters/**, /api/players/**, /api/playersUsername/**, /api/teams/**, /api/games/**
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/players/**/profiles/**, /api/players/**/profilesUsername
        - id: communication-service
          uri: lb://communication-service
          predicates:
            - Path=/api/chats/**, /api/chats/, /api/messages/, /api/chats/**/messages/**
