server:
  port: 8093

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #Rutas de cada servicio:
        - id: matchmaking-service
          uri: lb://matchmaking-service
          predicates:
            - Path=/matchmaking/**
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/profile/**
        - id: communication-service
          uri: lb://communication-service
          predicates:
            - Path=/communication/**
